export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const FETCH_FREE_VIDEOS = 'FETCH_FREE_VIDEOS';
export const FETCH_FREE_VIDEOS_SUCCESS = 'FETCH_FREE_VIDEOS_SUCCESS';
export const FETCH_FREE_VIDEOS_FAILURE = 'FETCH_FREE_VIDEOS_FAILURE';

export const FETCH_PREMIUM_VIDEOS = 'FETCH_PREMIUM_VIDEOS';
export const FETCH_PREMIUM_VIDEOS_SUCCESS = 'FETCH_PREMIUM_VIDEOS_SUCCESS';
export const FETCH_PREMIUM_VIDEOS_FAILURE = 'FETCH_PREMIUM_VIDEOS_FAILURE';

export const CLEAR_FREE_VIDEOS = 'CLEAR_FREE_VIDEOS';
export const CLEAR_FREE_VIDEOS_SUCCESS = 'CLEAR_FREE_VIDEOS_SUCCESS';
export const CLEAR_FREE_VIDEOS_FAILURE = 'CLEAR_FREE_VIDEOS_FAILURE';

export const CLEAR_PREMIUM_VIDEOS = 'CLEAR_PREMIUM_VIDEOS';
export const CLEAR_PREMIUM_VIDEOS_SUCCESS = 'CLEAR_PREMIUM_VIDEOS_SUCCESS';
export const CLEAR_PREMIUM_VIDEOS_FAILURE = 'CLEAR_PREMIUM_VIDEOS_FAILURE';

export const CONTACT_FORM = 'CONTACT_FORM';
export const CONTACT_FORM_SUCCESS = 'CONTACT_FORM_SUCCESS';
export const CONTACT_FORM_FAILURE = 'CONTACT_FORM_FAILURE';


export const PAYMENT_SUBMISSION = 'PAYMENT_SUBMISSION';
export const PAYMENT_SUBMISSION_SUCCESS = 'PAYMENT_SUBMISSION_SUCCESS';
export const PAYMENT_SUBMISSION_FAILURE = 'PAYMENT_SUBMISSION_FAILURE';
